In [1]:
# load in fits table
import numpy as np
from astropy.io import fits
from astropy.table import Table


In [2]:
data = Table.read('/Users/sp624AA/Downloads/test_Amata1.fits')
data2 = Table.read('/Users/sp624AA/Downloads/test_WD.fits')
data3 = Table.read('/Users/sp624AA/Downloads/SPV-SVX07_COSMOS_1.fits')

In [13]:
np.unique(data2['OBJ_GR'])

print(data[data['FIB_USE']==4]['OBJ_GR', 'FIB_USE', 'FIB_ROOT'])

  OBJ_GR  FIB_USE FIB_ROOT
   mag                    
--------- ------- --------
19.743027       4        1
18.245472       4        3
 17.92095       4        2
18.993298       4        2
20.139462       4        1
18.373125       4        3
19.308693       4        1
19.492002       4        1
19.173365       4        1
 19.06912       4        1
18.989832       4        3
19.839638       4        1
19.246065       4        1
20.221762       4        1
18.794899       4        2
20.157188       4        1
19.556091       4        1
 19.03379       4        1
19.703093       4        1


In [5]:
data2['FIB_ROOT']

1
2
3
1
2
3
1
2
3
1
2


In [12]:
np.unique(data['FIB_USE'])

1
3
4
5
--


In [6]:
np.unique(data3['OBJ_PMRA'], return_counts=True)

(<Column name='OBJ_PMRA' dtype='float64' unit='0.001 arcsec / yr' length=29>
          -180.02638
          -61.818035
           -44.87667
          -41.834015
  -36.68352604506363
           -27.03502
 -26.545294417802022
 -24.340150698000937
 -23.436122238621255
          -16.740805
 -12.031554910246086
  -9.720827114664509
                 ...
                 0.0
          0.19458659
  0.2718933970237496
            1.053414
           2.4920235
           5.4396925
            8.723371
            8.887864
           11.825693
  14.602593008950084
            25.35951
           26.702185,
 array([   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1, 2420,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1]))

In [10]:
np.unique(data3['OBJ_ROFF'])

0.0


In [14]:
np.unique(data3['OBJ_FLAG'], return_counts=True)

(<MaskedColumn name='OBJ_FLAG' dtype='int16' length=2>
  1
 --,
 array([ 852, 1596]))

In [18]:
np.unique(data3['FIB_ROOT'], return_counts=True)

(<MaskedColumn name='FIB_ROOT' dtype='int16' length=4>
 1
 2
 3
 4,
 array([812, 812, 812,  12]))

In [29]:
np.unique(data3['OBJ_SRV'][1610])

array([False])

In [ ]:
#!/usr/bin/env python3
"""
A script to check the fibinfos file for calibration targets and their G band magnitudes.
Usage:
python3 check_fibinfos.py path_to_fibinfos_file

Note, on Typhon, you need to specify python3 in CL.
"""

import numpy as np
import argparse
from astropy.table import Table

def check_fibinfos(file):

    fibinfos = Table.read(file) # Load fibinfos


    # Check if boolean array has at least 1 true value
    if not np.any(fibinfos['FIB_USE'] == 4):
        print("No targets given calibration designation in FIBINFO table (FIB_USE==4)")
        return

    calibs = fibinfos[fibinfos['FIB_USE'] == 4] # Extract CALIB column
    
    spectros = ['HR', 'LRA', 'LRB']
    spectro_fib_roots = [1, 2, 3]
    for i in range(len(spectros)):
        spectro=spectros[i]
        spectro_fib_root = spectro_fib_roots[i]
        spectro_calibs = calibs[calibs['FIB_ROOT'] == spectro_fib_root]

        print(f"Number of {spectro} calibrators: {len(spectro_calibs)}")
        
        print(f"Brighest G band estimate for {spectro} calibrators: {np.min(spectro_calibs['OBJ_GR'])}")

        print(f"All G band magnitudes for {spectro} calibrators:")
        print(spectro_calibs['OBJ_GR'])


def main():
    parser = argparse.ArgumentParser(description='Check fibinfos file for calibration targets')
    parser.add_argument('file', type=str, help='Path to fibinfos file')
    args = parser.parse_args()
    check_fibinfos(args.file)
    

if __name__ == "__main__":
    main()
